=== SolaceLabs/solace-ep-codegen/src/test/resources/ep-demo/schemas/NewOrder-Schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "countryCode": {
      "type": "string"
    },
    "requestId": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "storeId": {
      "type": "string"
    },
    "orderId": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "customer": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        }
      }
    },
    "items": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "productID": {
              "type": "string"
            },
            "productName": {
              "type": "string"
            },
            "quantity": {
              "type": "integer"
            },
            "size": {
              "type": "string"
            },
            "options": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                },
                {
                  "type": "string"
                }
              ]
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "productID": {
              "type": "string"
            },
            "productName": {
              "type": "string"
            },
            "quantity": {
              "type": "integer"
            }
          }
        }
      ]
    },
    "totalPrice": {
      "type": "number"
    },
    "pickupTime": {
      "type": "string"
    },
    "specialInstructions": {
      "type": "string"
    }
  }
}

=== SolaceLabs/solace-ep-codegen/src/test/resources/ep-demo/samples/NewOrder-Sample.json
{
  "countryCode": "USA",
  "requestId": "5440cc82-e3d2-44c2-a4da-4caf2a9cae3d",
  "source": "App",
  "storeId": "STORE023",
  "orderId": "ORD12355",
  "region" : "Ontario",
  "customer": {
    "name": "John Doe",
    "email": "john.doe@example.com",
    "phone": "123-456-7890"
  },
  "items": [
    {
      "productID": "COF001",
      "productName": "Americano",
      "quantity": 2,
      "size": "Medium",
      "options": ["Extra Shot", "Whipped Cream"]
    },
    {
      "productID": "PST001",
      "productName": "Chocolate Croissant",
      "quantity": 1
    }
  ],
  "totalPrice": 12.50,
  "pickupTime": "2024-01-05T14:30:00",
  "specialInstructions": "Please make it extra hot."
}
